redis.call('SET', 'foo:bar:test', '1')
redis.call('SET', 'foo:bar:test:', '2')
redis.call('SET', 'foo:bar:test|', '3')
redis.call('SET', 'foo:bar:test:deep', '4')
redis.call('SET', 'foo:bar:test:deep2', '4')
redis.call('SET', 'foo:bar:test:deep3', '4')
redis.call('SET', 'foo:bar:test:deep5', '4')
redis.call('SET', 'foo:bar:test:deep:and-long', 'This is a very long string')
redis.call('SET', 'foo:bar:test2', '5')
